name: Upload Affected Targets
on: pull_request

jobs:
  upload_affected_targets:
    name: Upload Affected Targets
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Upload Affected Targets
        uses: nikhilbirmiwal/hello-world-composite-action@v47 # TODO: Move this to a different repo.
