on: pull_request

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run bazel-diff for ${{ github.event.pull_request.number }}
    steps:
      - name: Checkout Customer Repo
        uses: actions/checkout@v3

      - name: Expected New Hash
        run: echo ${{ github.event.pull_request.head.sha }}
        shell: bash

      - name: Expected Old Hash
        run: echo ${{ github.event.pull_request.base.sha }}
        shell: bash

      - name: Run Upload Affected Targets
        uses: nikhilbirmiwal/hello-world-composite-action@v1