on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run bazel-diff on this command
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: nikhilbirmiwal/hello-world-composite-action@v24
