name: Pull Request
run-name: Pull Request for ${{ github.ref_name }} by ${{ github.actor }}

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - trunk-merge/**

# Allows the automerge bot PR job to comment on dependabot PRs
permissions: write-all

jobs:
  noop:
    runs-on: ubuntu-latest
    name: Echo test
    steps:
      - name: Echo foo
        run: echo foo
